name: Build snapshot

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '1.8', '11' ]

    name: build java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  deploy:
    runs-on: ubuntu-latest
    
    name: deploy snapshot
    steps:
      - uses: actions/checkout@v1
      - name: Set release version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:11}"-SNAPSHOT")
      - name: Build and deploy to Sonatype snapshot
        uses: digipost/action-maven-publish@1.1.0
        with:
          sonatype_secrets: ${{ secrets.sonatype_secrets }}
          release_version: ${{ env.RELEASE_VERSION }}
          perform_release: false
